# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2434f7d9388cde7cd724f1684e324857"
name = "new-app"
handle = "new-app-1100"
application_url = "https://headphones-contractor-ssl-intl.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_inventory,read_product_listings,read_products,write_content,write_discounts,write_products"

[auth]
redirect_urls = ["https://headphones-contractor-ssl-intl.trycloudflare.com/auth/callback", "https://headphones-contractor-ssl-intl.trycloudflare.com/auth/shopify/callback", "https://headphones-contractor-ssl-intl.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
