# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "60da4802f5033c2b2ef0012603ad2e66"
name = "new-version"
handle = "new-version-7"
application_url = "https://topics-professor-solaris-determined.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_inventory,read_product_listings,read_products,write_content,write_discounts,write_products"

[auth]
redirect_urls = ["https://topics-professor-solaris-determined.trycloudflare.com/auth/callback", "https://topics-professor-solaris-determined.trycloudflare.com/auth/shopify/callback", "https://topics-professor-solaris-determined.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
