# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1667f83f4a1accab72a4d73ac49f0757"
name = "new-app"
handle = "new-app-1099"
application_url = "https://url-martin-tigers-sell.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_inventory,read_product_listings,read_products,write_content,write_discounts,write_products"

[auth]
redirect_urls = ["https://url-martin-tigers-sell.trycloudflare.com/auth/callback", "https://url-martin-tigers-sell.trycloudflare.com/auth/shopify/callback", "https://url-martin-tigers-sell.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
