# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ebe9ea81368d82e604a028fa4202680f"
name = "new-app"
handle = "new-app-692"
application_url = "https://screenshots-as-continuously-possess.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://screenshots-as-continuously-possess.trycloudflare.com/auth/callback", "https://screenshots-as-continuously-possess.trycloudflare.com/auth/shopify/callback", "https://screenshots-as-continuously-possess.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
